steps:
  - command: .buildkite/run
    plugins:
      - mynewsdesk/devops-buildkite-cache#master

  - command: .buildkite/build-and-push-docker-image
    key: docker_image
    label: ":docker: Build and push docker image"

  - wait

  - label: 🚀 Deploy master branch to production
    trigger: $BUILDKITE_PIPELINE_SLUG-deploy
    async: true
    branches: master
    build:
      commit: $BUILDKITE_COMMIT
      branch: $BUILDKITE_BRANCH
      env:
        DEPLOYMENT_TARGET: devops-talos-manager

  - block: 🚀 Deploy this build...
    fields:
      - select: Select a server
        key: deployment-target
        default: devops-talos-manager
        options:
          - value: devops-talos-manager
            label: devops-talos-manager

  - command: .buildkite/trigger-deploy
