on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: depot/build-push-action@v1
        with:
          project: 8cd70jhtnd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            reclaimthestack/talos-manager:latest
            reclaimthestack/talos-manager:sha-${{ github.sha }}
